### ISSUE TITLE
Suggestion: add the "mcnp" topic to this repo.

### ISSUE THREAD

**Issue by MicahGale** [mjeroutek/MCNP-Syntax-Highlighting#1]
There is a growing github tag: [mcnp](https://github.com/topics/mcnp). I would suggest adding this to your project to improve its visibility. Here's a guide on how to do that: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by mjeroutek** [comment]
Hi Micah,

Thank you for letting me know about tags! I appreciate you linking me to the guide for adding them. I've just added several applicable tags to the repository including the specific one you mentioned.

**Comment by MicahGale** [comment]
Awesome! Welcome to the MCNP topic family.
